name: ChestPlus
version: 1.0
main: com.angie.chestplus.ChestPlus
api-version: 1.20
author: Angie
description: A customizable virtual chest plugin for personal storage.

commands:
  chest:
    description: Opens your personal storage chest.
    usage: /<command>
    permission: chestplus.command
    permission-message: "&cYou do not have permission to use this command."
    tab-completer: com.angie.chestplus.command.StorageTabCompleter

permissions:
  chestplus.command:
    description: Allows use of the /chest command
    default: true

  chestplus.open.1:
    description: Access to Chest #1
    default: true
  chestplus.open.2:
    description: Access to Chest #2
    default: op
  chestplus.open.3:
    description: Access to Chest #3
    default: op
  chestplus.open.4:
    description: Access to Chest #4
    default: op
  chestplus.open.5:
    description: Access to Chest #5
    default: op

  chestplus.reload:
    description: Allows reloading of the ChestPlus configuration
    default: op

  chestplus.open.other:
    description: Allows opening other players' chests
    default: op
