storage:
  max-slots: 5  # Maximum number of personal chests

  chests:
    1:
      permission: "chestplus.open.1"
      size: 45
    2:
      permission: "chestplus.open.2"
      size: 45
    3:
      permission: "chestplus.open.3"
      size: 45
    4:
      permission: "chestplus.open.4"
      size: 45
    5:
      permission: "chestplus.open.5"
      size: 45
